apiVersion: v2
name: external-dns
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
sources:
  - https://github.com/kubernetes-sigs/external-dns/
dependencies:
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.19.0
    alias: external-dns-pihole
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.19.0
    alias: external-dns-cloudflare

type: application

# renovate: datasource=helm depName=external-dns repository=https://kubernetes-sigs.github.io/external-dns/
version: 1.18.0

# renovate: datasource=github-releases depName=kubernetes-sigs/external-dns
appVersion: v0.20.0

keywords:
  - kubernetes
  - externaldns
  - external-dns
  - dns
  - service
  - ingress
